### ISSUE TITLE
Unhandled rejection Error: problem parsing null.tooling.cache. Ensure it is valid JSON!

### ISSUE THREAD

**Issue by klonos** [lando/core-next#35]
I was facing some issues with my drush for Backdrop, so I have upgraded from RC17 to RC20, and then `.lndo.site` domains stoped working (#1490). So I removed the `~/.lando` directory, as per suggestion in that issue and also in https://docs.lando.dev/guides/updating-to-rc2.html#removing-lando

Now, things work (`lando start`, `lando stop`, `lando destroy` etc.), but I get this error when running commands like `lando list` and `lando version`:

```bash
Unhandled rejection Error: There was a problem with parsing /Users/name/.lando/cache/null.tooling.cache. Ensure it is valid JSON! Error: ENOENT: no such file or directory, open '/Users/name/.lando/cache/null.tooling.cache'
    at loadCacheFile (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at Object.exports.getTasks (/snapshot/lando/build/cli/lib/bootstrap.js:0:0)
    at lando.bootstrap.then.lando.getApp.init.then (/snapshot/lando/build/cli/bin/lando.js:0:0)
From previous event:
    at lando.bootstrap.then.lando (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
From previous event:
    at Object.<anonymous> (/snapshot/lando/build/cli/bin/lando.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1309:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)
```

...heres a listing of my `.lando/cache` directory:

```bash
total 80
drwxr-xr-x@ 11 greg  staff   352  1 Sep 23:43 .
drwxr-xr-x@ 10 greg  staff   320  1 Sep 00:27 ..
-rw-r--r--@  1 greg  staff  1532  1 Sep 23:43 .compose.cache
-rw-r--r--@  1 greg  staff  1112  1 Sep 23:43 .tooling.cache
-rw-r--r--@  1 greg  staff    21  1 Sep 00:42 2382.build.lock
-rw-r--r--@  1 greg  staff  1735  1 Sep 07:05 2382.compose.cache
-rw-r--r--@  1 greg  staff  1112  1 Sep 07:05 2382.tooling.cache
-rw-r--r--   1 greg  staff  7138  1 Sep 23:43 _.tasks.cache
-rw-r--r--@  1 greg  staff    39  1 Sep 00:24 id
-rw-r--r--@  1 greg  staff    28  1 Sep 23:33 proxyCache
```

**Tell us about your setup**

v3.0.0-rc.20 on Mac OS 10.14.6

**Tell us about your `.lando.yml`**

N/A ...happens with commands like `lando version`.

**Tell us about the command you were running**

`lando list`, `lando version`

**Comment by ben-hamelin** [comment]
Replacing our project name with all lower case characters solved our issue as well.
